# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2131532452bb52c33fcc5fda1aeb7bb357a059f79015c824451641b7c3efffb24bf0d9be682492a13a00cf37deb1cb93b45114db4fce7effd27a77cedb904014

test:
  secret_key_base: 376a79147ee43a6a063c7a81d856d29197ea960335abe45fcc5aca7f775d67f7b85c8760208c8df962a404f494f76caa89bc1c556eb8e00477143c8a2e0f23af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
